package com.zwy.demo.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.zwy.demo.dbbean.HomeTitle;
import com.zwy.demo.dbbean.ImageBean;

import com.zwy.demo.db.HomeTitleDao;
import com.zwy.demo.db.ImageBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig homeTitleDaoConfig;
    private final DaoConfig imageBeanDaoConfig;

    private final HomeTitleDao homeTitleDao;
    private final ImageBeanDao imageBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        homeTitleDaoConfig = daoConfigMap.get(HomeTitleDao.class).clone();
        homeTitleDaoConfig.initIdentityScope(type);

        imageBeanDaoConfig = daoConfigMap.get(ImageBeanDao.class).clone();
        imageBeanDaoConfig.initIdentityScope(type);

        homeTitleDao = new HomeTitleDao(homeTitleDaoConfig, this);
        imageBeanDao = new ImageBeanDao(imageBeanDaoConfig, this);

        registerDao(HomeTitle.class, homeTitleDao);
        registerDao(ImageBean.class, imageBeanDao);
    }
    
    public void clear() {
        homeTitleDaoConfig.clearIdentityScope();
        imageBeanDaoConfig.clearIdentityScope();
    }

    public HomeTitleDao getHomeTitleDao() {
        return homeTitleDao;
    }

    public ImageBeanDao getImageBeanDao() {
        return imageBeanDao;
    }

}
